org.gradle.jvmargs=-Xmx6g -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.jetifier.ignorelist=jackson-core
android.enableR8.fullMode=false
# These fields were added to keep the build configuration the same as before
# AGP 8.
# See more details here: https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes#default-changes
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
kotlin.jvm.target.validation.mode=WARNING